# Based on https://github.com/wp-cli/scaffold-command/blob/f9bad3dd7224d5684d950d31c486df70905e386f/templates/plugin-github.mustache
name: WordPress Test

on: [push]

env:
  WP_TESTS_DIR: /github/home/wp-tests/wordpress-tests-lib
  WP_CORE_DIR: /github/home/wp-tests/wordpress

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.2]
        wordpress-version: [latest]
    container:
      image: junaidbhura/wp-tests:php-${{ matrix.php-version }}
    services:
      mysql:
        image: mysql:5.7.27
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
      - name: Start Sendira
        uses: upgundecha/start-sendria-github-action@v1.0.0
        with:
          smtp-port: 1025
          http-port: 1080

      - name: List docker containers
        continue-on-error: true
        if: ${{ true }}
        run: |
          docker ps -a

      - name: Test
        continue-on-error: true
        if: ${{ true }}
        run: |
          curl -LI http://127.0.0.1:1080

      - name: Localhost Test
        continue-on-error: true
        if: ${{ true }}
        run: |
          curl -LI http://localhost:1080

      - name: netstat Test
        continue-on-error: true
        if: ${{ true }}
        run: |
          netstat -tulnp

      - name: iptables Test
        continue-on-error: true
        if: ${{ true }}
        run: |
          iptables -L

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Composer dependencies
        run: |
          composer install --no-dev
          composer global require "phpunit/phpunit=6.1.0"
          composer global require "yoast/phpunit-polyfills=1.0.3"

      - name: Install WordPress test suite
        run: bash bin/install-wp-tests.sh wordpress_test root root mysql ${{ matrix.wordpress-version }}

      - name: Tests
        run: $HOME/.composer/vendor/bin/phpunit --config=phpunit-integration.xml
